In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("data/customer_support_tickets.csv")

In [4]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [5]:
df["text"] = (
    df["Ticket Subject"].astype(str) + " " +
    df["Ticket Description"].astype(str)
)

In [6]:
df = df[["text", "Ticket Type", "Ticket Priority"]]

In [7]:
df.dropna(subset=["Ticket Type", "Ticket Priority"], inplace=True)

In [8]:
df.head()

,text,Ticket Type,Ticket Priority
0,Product setup I'm having an issue with the {pr...,Technical issue,Critical
1,Peripheral compatibility I'm having an issue w...,Technical issue,Critical
2,Network problem I'm facing a problem with my {...,Technical issue,Low
3,Account access I'm having an issue with the {p...,Billing inquiry,Low
4,Data loss I'm having an issue with the {produc...,Billing inquiry,Low

In [12]:
df['Ticket Type'].unique()

array(['Technical issue', 'Billing inquiry', 'Cancellation request',
       'Product inquiry', 'Refund request'], dtype=object)

In [9]:
df["text"].fillna("", inplace=True)

C:\Users\Ayush\AppData\Local\Temp\ipykernel_20348\2582040697.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["text"].fillna("", inplace=True)

In [10]:
df.to_csv("data/processed_data.csv")